In [1]:
import pandas as pd
import numpy as np

df = pd.read_csv("retail_sales_dataset.csv")

df.head()

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
0,ORD-03903,2024-08-15,CUST32603,Aarav Mehta,39.0,Other,Central,Raipur,Groceries,Sugar,...,346.32,NaN,4043.14,289.18,56.04,Debit Card,NaN,True,Returned,7.0
1,ORD-02198,2022-08-16,CUST07881,Sanjay Verma,28.0,Male,West,Mumbai,Beauty,Sunscreen,...,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5.0,False,Delivered,2.0
2,ORD-01348,2021-08-29,CUST49296,Pooja Sharma,41.0,Other,West,Surat,Furniture,Sofa,...,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4.0,False,Delivered,5.0
3,ORD-02076,2022-07-05,CUST05587,Priya Reddy,29.0,Other,West,Ahmedabad,Furniture,Bed Frame,...,22071.92,0.17,262066.11,66644.99,54.47,EMI,3.0,False,Delivered,4.0
4,ORD-00287,2020-05-07,CUST58035,Ritu Sharma,9.0,Male,Central,Nagpur,Groceries,Cooking Oil,...,320.06,0.31,323.95,31.38,48.81,Net Banking,4.0,False,Pending,4.0

In [2]:
print("Rows and Columns:", df.shape)

print("\nColumn Names:")
print(df.columns)

print("\nData Types:")
print(df.dtypes)

Rows and Columns: (4310, 21)

Column Names:
Index(['order_id', 'order_date', 'customer_id', 'customer_name', 'age',
       'gender', 'region', 'city', 'product_category', 'product_name',
       'quantity', 'unit_price', 'discount_pct', 'sales_amount', 'profit',
       'shipping_cost', 'payment_method', 'customer_satisfaction',
       'return_flag', 'order_status', 'days_to_ship'],
      dtype='str')

Data Types:
order_id                     str
order_date                   str
customer_id                  str
customer_name                str
age                      float64
gender                       str
region                       str
city                         str
product_category             str
product_name                 str
quantity                 float64
unit_price               float64
discount_pct             float64
sales_amount             float64
profit                   float64
shipping_cost            float64
payment_method               str
customer_satisfaction    float64
return_flag               object
order_status                 str
days_to_ship             float64
dtype: object

In [3]:
quality_report = pd.DataFrame({
    'Missing Values': df.isnull().sum(),
    'Missing %': (df.isnull().sum() / len(df) * 100).round(2),
    'Data Type': df.dtypes.astype(str),
    'Unique Values': df.nunique()
})

quality_report

                       Missing Values  Missing % Data Type  Unique Values
order_id                           30       0.70       str           4200
order_date                         30       0.70       str           1837
customer_id                        30       0.70       str           4112
customer_name                      30       0.70       str            400
age                               160       3.71   float64             80
gender                             30       0.70       str             11
region                             30       0.70       str              5
city                               30       0.70       str             20
product_category                   30       0.70       str              7
product_name                       30       0.70       str             42
quantity                          140       3.25   float64             13
unit_price                         30       0.70   float64           4191
discount_pct                      167       3.87   float64             41
sales_amount                       30       0.70   float64           4199
profit                             30       0.70   float64           4179
shipping_cost                      30       0.70   float64           3140
payment_method                     30       0.70       str              6
customer_satisfaction             378       8.77   float64              5
return_flag                        30       0.70    object              2
order_status                       30       0.70       str              9
days_to_ship                      130       3.02   float64             14

In [4]:
duplicate_count = df.duplicated().sum()

print("Duplicate rows:", duplicate_count)

Duplicate rows: 109

In [5]:
df = df.drop_duplicates()

print("Rows after removing duplicates:", len(df))

Rows after removing duplicates: 4201

## Duplicate Removal

Duplicate rows were identified using pandas' `duplicated()` method and removed using `drop_duplicates()`. Removing exact duplicate records prevents the same transaction from being counted multiple times during analysis.

In [6]:
empty_rows = df.isnull().all(axis=1).sum()

print("Completely empty rows:", empty_rows)

Completely empty rows: 1

In [8]:
df = df.dropna(how='all')

In [9]:
df_raw = df.copy()

print("Original dataset copy created successfully!")

Original dataset copy created successfully!

In [10]:
missing_values = df.isnull().sum()

missing_values[missing_values > 0]

age                      125
quantity                 108
discount_pct             135
customer_satisfaction    346
days_to_ship              97
dtype: int64

In [11]:
numeric_columns = [
    'age',
    'quantity',
    'discount_pct',
    'customer_satisfaction',
    'days_to_ship'
]

for col in numeric_columns:
    df[col] = df[col].fillna(df[col].median())

print("Missing numerical values handled.")

Missing numerical values handled.

In [12]:
df[numeric_columns].isnull().sum()

age                      0
quantity                 0
discount_pct             0
customer_satisfaction    0
days_to_ship             0
dtype: int64

## Missing Numerical Values

Missing values in numerical columns were handled using median imputation. Median was selected because the dataset contains extreme values and is therefore less sensitive to outliers than the mean.

In [13]:
categorical_columns = df.select_dtypes(
    include=['object', 'string']
).columns

print(df[categorical_columns].isnull().sum())

order_id            0
order_date          0
customer_id         0
customer_name       0
gender              0
region              0
city                0
product_category    0
product_name        0
payment_method      0
return_flag         0
order_status        0
dtype: int64

In [14]:
for col in categorical_columns:
    if df[col].isnull().sum() > 0:
        df[col] = df[col].fillna(df[col].mode()[0])

print("Missing categorical values handled.")

Missing categorical values handled.

In [15]:
df[categorical_columns].isnull().sum()

order_id            0
order_date          0
customer_id         0
customer_name       0
gender              0
region              0
city                0
product_category    0
product_name        0
payment_method      0
return_flag         0
order_status        0
dtype: int64

In [16]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [17]:
df['order_date'] = pd.to_datetime(
    df['order_date'],
    dayfirst=True,
    errors='coerce'
)

C:\Users\Dell\AppData\Local\Temp\ipykernel_9760\679945132.py:1: UserWarning: Parsing dates in %Y-%m-%d format when dayfirst=True was specified. Pass `dayfirst=False` or specify a format to silence this warning.
  df['order_date'] = pd.to_datetime(

In [18]:
print(df['order_date'].dtype)
print("Missing dates:", df['order_date'].isnull().sum())

datetime64[us]
Missing dates: 267

In [19]:
df['gender'] = df['gender'].astype(str).str.strip()

df['gender'] = df['gender'].replace({
    'M': 'Male',
    'm': 'Male',
    'MALE': 'Male',
    'male': 'Male',
    'F': 'Female',
    'f': 'Female',
    'FEMALE': 'Female',
    'female': 'Female'
})

In [20]:
df['gender'].value_counts()

gender
Other     1419
Male      1408
Female    1373
Name: count, dtype: int64

In [21]:
df['order_status'] = (
    df['order_status']
    .astype(str)
    .str.strip()
    .str.title()
)

df['order_status'].value_counts()

order_status
Delivered    2731
Returned      612
Cancelled     346
Shipped       327
Pending       184
Name: count, dtype: int64

In [22]:
categorical_to_clean = [
    'region',
    'city',
    'product_category',
    'product_name',
    'payment_method'
]

for col in categorical_to_clean:
    df[col] = (
        df[col]
        .astype(str)
        .str.strip()
        .str.title()
    )

In [23]:
df['order_id'] = df['order_id'].astype('string')
df['customer_id'] = df['customer_id'].astype('string')

numeric_columns_all = [
    'age',
    'quantity',
    'unit_price',
    'discount_pct',
    'sales_amount',
    'profit',
    'shipping_cost',
    'customer_satisfaction',
    'days_to_ship'
]

for col in numeric_columns_all:
    df[col] = pd.to_numeric(df[col], errors='coerce')

In [24]:
df.dtypes

order_id                         string
order_date               datetime64[us]
customer_id                      string
customer_name                       str
age                             float64
gender                              str
region                              str
city                                str
product_category                    str
product_name                        str
quantity                        float64
unit_price                      float64
discount_pct                    float64
sales_amount                    float64
profit                          float64
shipping_cost                   float64
payment_method                      str
customer_satisfaction           float64
return_flag                      object
order_status                        str
days_to_ship                    float64
dtype: object

In [25]:
invalid_age = df[
    (df['age'] < 18) |
    (df['age'] > 100)
]

print("Invalid age records:", len(invalid_age))

invalid_age[['order_id', 'age']].head(20)

Invalid age records: 337

      order_id    age
4    ORD-00287    9.0
9    ORD-00105   17.0
11   ORD-01701   14.0
12   ORD-02270   15.0
17   ORD-03257   15.0
20   ORD-01978   15.0
42   ORD-00415   -6.0
44   ORD-00757  999.0
65   ORD-00879   17.0
79   ORD-00058   16.0
89   ORD-02956   10.0
106  ORD-00943   14.0
107  ORD-03731   11.0
108  ORD-02485   12.0
131  ORD-03678   16.0
132  ORD-01310   14.0
147  ORD-02723   12.0
148  ORD-00073  999.0
182  ORD-02004   17.0
191  ORD-02680   14.0

In [26]:
df.loc[
    (df['age'] < 18) |
    (df['age'] > 100),
    'age'
] = np.nan

df['age'] = df['age'].fillna(df['age'].median())

In [27]:
print("Minimum age:", df['age'].min())
print("Maximum age:", df['age'].max())

Minimum age: 18.0
Maximum age: 72.0

In [28]:
invalid_quantity = df[df['quantity'] <= 0]

print("Invalid quantity records:", len(invalid_quantity))

Invalid quantity records: 18

In [29]:
df.loc[df['quantity'] <= 0, 'quantity'] = np.nan

df['quantity'] = df['quantity'].fillna(
    df['quantity'].median()
)

In [30]:
print("Minimum quantity:", df['quantity'].min())

Minimum quantity: 1.0

In [31]:
print(
    "Invalid shipping costs:",
    (df['shipping_cost'] < 0).sum()
)

Invalid shipping costs: 2

In [32]:
df.loc[
    df['shipping_cost'] < 0,
    'shipping_cost'
] = np.nan

df['shipping_cost'] = df['shipping_cost'].fillna(
    df['shipping_cost'].median()
)

In [33]:
print(
    "Invalid shipping days:",
    (df['days_to_ship'] < 0).sum()
)

Invalid shipping days: 5

In [34]:
df.loc[
    df['days_to_ship'] < 0,
    'days_to_ship'
] = np.nan

df['days_to_ship'] = df['days_to_ship'].fillna(
    df['days_to_ship'].median()
)

In [35]:
invalid_discount = df[
    (df['discount_pct'] < 0) |
    (df['discount_pct'] > 1)
]

print("Invalid discount values:", len(invalid_discount))

Invalid discount values: 0

In [36]:
invalid_satisfaction = df[
    (df['customer_satisfaction'] < 1) |
    (df['customer_satisfaction'] > 5)
]

print(
    "Invalid satisfaction values:",
    len(invalid_satisfaction)
)

Invalid satisfaction values: 0

In [37]:
def find_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]

    return outliers, lower_bound, upper_bound

In [38]:
def find_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]

    return outliers, lower_bound, upper_bound

## Outlier Detection

The Interquartile Range (IQR) method was used to identify potential outliers in numerical variables.

Potential outliers were not automatically removed because extreme sales, profit, quantity, or price values may represent legitimate business transactions. Clearly implausible values, such as negative ages and negative shipping days, were treated separately as data-quality errors.

This approach helps preserve potentially meaningful business information while correcting values that are logically invalid.

In [39]:
print("Total missing values:", df.isnull().sum().sum())

df.isnull().sum()

Total missing values: 267

order_id                   0
order_date               267
customer_id                0
customer_name              0
age                        0
gender                     0
region                     0
city                       0
product_category           0
product_name               0
quantity                   0
unit_price                 0
discount_pct               0
sales_amount               0
profit                     0
shipping_cost              0
payment_method             0
customer_satisfaction      0
return_flag                0
order_status               0
days_to_ship               0
dtype: int64

In [40]:
print(df['order_date'].min())
print(df['order_date'].max())

2020-01-01 00:00:00
2024-12-30 00:00:00

In [41]:
median_date = df['order_date'].dropna().median()

df['order_date'] = df['order_date'].fillna(median_date)

print("Missing dates after cleaning:", df['order_date'].isnull().sum())

Missing dates after cleaning: 0

In [42]:
print("Total missing values:", df.isnull().sum().sum())

Total missing values: 0

In [43]:
df.isnull().sum()

order_id                 0
order_date               0
customer_id              0
customer_name            0
age                      0
gender                   0
region                   0
city                     0
product_category         0
product_name             0
quantity                 0
unit_price               0
discount_pct             0
sales_amount             0
profit                   0
shipping_cost            0
payment_method           0
customer_satisfaction    0
return_flag              0
order_status             0
days_to_ship             0
dtype: int64

In [44]:
print("Duplicate rows:", df.duplicated().sum())

Duplicate rows: 0

In [45]:
df.info()

<class 'pandas.DataFrame'>
Index: 4200 entries, 0 to 4309
Data columns (total 21 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   order_id               4200 non-null   string
 1   order_date             4200 non-null   datetime64[us]
 2   customer_id            4200 non-null   string
 3   customer_name          4200 non-null   str
 4   age                    4200 non-null   float64
 5   gender                 4200 non-null   str
 6   region                 4200 non-null   str
 7   city                   4200 non-null   str
 8   product_category       4200 non-null   str
 9   product_name           4200 non-null   str
 10  quantity               4200 non-null   float64
 11  unit_price             4200 non-null   float64
 12  discount_pct           4200 non-null   float64
 13  sales_amount           4200 non-null   float64
 14  profit                 4200 non-null   float64
 15  shipping_cost          4200 non-null   float64
 16  payment_method         4200 non-null   str
 17  customer_satisfaction  4200 non-null   float64
 18  return_flag            4200 non-null   object
 19  order_status           4200 non-null   str
 20  days_to_ship           4200 non-null   float64
dtypes: datetime64[us](1), float64(9), object(1), str(8), string(2)
memory usage: 721.9+ KB

In [46]:
df.head()

,order_id,order_date,customer_id,customer_name,age,gender,region,city,product_category,product_name,...,unit_price,discount_pct,sales_amount,profit,shipping_cost,payment_method,customer_satisfaction,return_flag,order_status,days_to_ship
0,ORD-03903,2024-08-15,CUST32603,Aarav Mehta,39.0,Other,Central,Raipur,Groceries,Sugar,...,346.32,0.21,4043.14,289.18,56.04,Debit Card,3.0,True,Returned,7.0
1,ORD-02198,2022-08-16,CUST07881,Sanjay Verma,28.0,Male,West,Mumbai,Beauty,Sunscreen,...,858.66,0.08,9147.31,5355.56,64.49,Debit Card,5.0,False,Delivered,2.0
2,ORD-01348,2021-08-29,CUST49296,Pooja Sharma,41.0,Other,West,Surat,Furniture,Sofa,...,25941.32,0.14,110156.97,36956.51,67.65,Debit Card,4.0,False,Delivered,5.0
3,ORD-02076,2022-07-05,CUST05587,Priya Reddy,29.0,Other,West,Ahmedabad,Furniture,Bed Frame,...,22071.92,0.17,262066.11,66644.99,54.47,Emi,3.0,False,Delivered,4.0
4,ORD-00287,2020-05-07,CUST58035,Ritu Sharma,35.0,Male,Central,Nagpur,Groceries,Cooking Oil,...,320.06,0.31,323.95,31.38,48.81,Net Banking,4.0,False,Pending,4.0

In [47]:
df.describe()

,order_date,age,quantity,unit_price,discount_pct,sales_amount,profit,shipping_cost,customer_satisfaction,days_to_ship
count,4200,4200.000000,4200.000000,4200.000000,4200.000000,4.200000e+03,4.200000e+03,4200.000000,4200.000000,4200.000000
mean,2022-07-05 21:14:24,35.938810,7.379762,10702.729695,0.202138,6.292138e+04,1.179028e+04,63.410774,3.016429,5.639762
min,2020-01-01 00:00:00,18.000000,1.000000,50.260000,0.000000,3.945000e+01,1.560000e+00,0.510000,1.000000,0.000000
25%,2021-05-17 18:00:00,29.000000,3.000000,680.817500,0.100000,2.472295e+03,7.120700e+02,50.855000,2.000000,3.000000
50%,2022-07-10 00:00:00,35.000000,5.000000,2246.005000,0.210000,9.647895e+03,3.169875e+03,63.465000,3.000000,6.000000
75%,2023-08-22 00:00:00,42.000000,8.000000,12828.977500,0.300000,5.052485e+04,1.051096e+04,75.655000,4.000000,8.000000
max,2024-12-30 00:00:00,72.000000,999.000000,79957.920000,0.400000,1.736031e+07,2.445648e+06,133.350000,5.000000,100.000000
std,NaN,9.759251,43.418535,17408.776463,0.116126,3.195126e+05,5.335219e+04,18.258900,1.354508,4.142208

In [48]:
def find_outliers_iqr(data, column):
    Q1 = data[column].quantile(0.25)
    Q3 = data[column].quantile(0.75)

    IQR = Q3 - Q1

    lower_bound = Q1 - 1.5 * IQR
    upper_bound = Q3 + 1.5 * IQR

    outliers = data[
        (data[column] < lower_bound) |
        (data[column] > upper_bound)
    ]

    return outliers, lower_bound, upper_bound

In [49]:
columns_to_check = [
    'age',
    'quantity',
    'unit_price',
    'sales_amount',
    'profit',
    'shipping_cost',
    'days_to_ship'
]

for col in columns_to_check:
    outliers, lower, upper = find_outliers_iqr(df, col)

    print(
        col,
        "→ Outliers:", len(outliers),
        "| Lower:", round(lower, 2),
        "| Upper:", round(upper, 2)
    )

age → Outliers: 39 | Lower: 9.5 | Upper: 61.5
quantity → Outliers: 8 | Lower: -4.5 | Upper: 15.5
unit_price → Outliers: 467 | Lower: -17541.42 | Upper: 31051.22
sales_amount → Outliers: 582 | Lower: -69606.54 | Upper: 122603.68
profit → Outliers: 541 | Lower: -13986.26 | Upper: 25209.29
shipping_cost → Outliers: 18 | Lower: 13.66 | Upper: 112.85
days_to_ship → Outliers: 6 | Lower: -4.5 | Upper: 15.5

## Outlier Detection

The Interquartile Range (IQR) method was used to identify potential outliers in numerical variables.

Potential outliers were not automatically removed because extreme values in sales, profit, quantity, and unit price may represent legitimate business transactions. Clearly invalid values, such as negative ages, negative quantities, negative shipping costs, and negative shipping days, were corrected separately.

In [50]:
before_summary = pd.DataFrame({
    'Rows': [len(df_raw)],
    'Columns': [df_raw.shape[1]],
    'Duplicate Rows': [df_raw.duplicated().sum()],
    'Missing Values': [df_raw.isnull().sum().sum()]
})

after_summary = pd.DataFrame({
    'Rows': [len(df)],
    'Columns': [df.shape[1]],
    'Duplicate Rows': [df.duplicated().sum()],
    'Missing Values': [df.isnull().sum().sum()]
})

comparison = pd.concat(
    [before_summary, after_summary]
)

comparison.index = [
    'Before Cleaning',
    'After Cleaning'
]

comparison

                 Rows  Columns  Duplicate Rows  Missing Values
Before Cleaning  4200       21               0             811
After Cleaning   4200       21               0               0

In [51]:
df.to_csv(
    "retail_sales_dataset_cleaned.csv",
    index=False
)

print("Cleaned dataset saved successfully!")

Cleaned dataset saved successfully!

In [52]:
print("FINAL DATA QUALITY CHECK")
print("------------------------")

print("Rows:", df.shape[0])
print("Columns:", df.shape[1])
print("Missing values:", df.isnull().sum().sum())
print("Duplicate rows:", df.duplicated().sum())
print("Minimum age:", df['age'].min())
print("Maximum age:", df['age'].max())
print("Minimum quantity:", df['quantity'].min())
print("Minimum shipping cost:", df['shipping_cost'].min())
print("Minimum shipping days:", df['days_to_ship'].min())
print("Date type:", df['order_date'].dtype)

FINAL DATA QUALITY CHECK
------------------------
Rows: 4200
Columns: 21
Missing values: 0
Duplicate rows: 0
Minimum age: 18.0
Maximum age: 72.0
Minimum quantity: 1.0
Minimum shipping cost: 0.51
Minimum shipping days: 0.0
Date type: datetime64[us]

# Conclusion

The Indian Retail Sales dataset was successfully cleaned and transformed into an analysis-ready dataset.

### Data Cleaning Performed

- Inspected the dataset structure, data types, missing values, and duplicate records.
- Identified and removed duplicate rows.
- Identified completely empty records.
- Handled missing numerical values using median imputation.
- Handled missing categorical values using mode imputation.
- Converted order dates into datetime format.
- Handled unparseable and missing order dates.
- Standardised inconsistent categorical values such as gender and order status.
- Corrected data types for identifier and numerical columns.
- Identified and corrected implausible customer ages.
- Corrected invalid negative quantities.
- Corrected negative shipping costs.
- Corrected negative shipping days.
- Validated discount percentages and customer satisfaction ratings.
- Used the IQR method to identify potential numerical outliers.
- Retained potentially legitimate business outliers rather than automatically deleting them.
- Created a before-versus-after data quality comparison.
- Exported the cleaned dataset as `retail_sales_dataset_cleaned.csv`.

The resulting dataset is more consistent, complete, and suitable for further exploratory analysis and business intelligence applications.